import React, {
  useState,
  useCallback,
  useMemo,
  useEffect,
  useRef,
} from "react";
import InfiniteGraph from "./components/InfiniteGraph";
import Controls from "./components/Controls";
import { Viewport, Theme, Point } from "./types";
import {
  createTransformFunction,
  gcd,
  gcdBigInt,
  getSmallestPrimeFactor,
  getSmallestPrimeFactorBigInt,
  splitTopLevelExpressions,
} from "./utils/math";
import { getRowOffset, getRowShiftMagnitude, pointKey } from "./utils/grid";
import {
  compileMoveRightPredicate,
  DEFAULT_MOVE_RIGHT_EXPR,
} from "./utils/moveRule";
import {
  findGroundPoint,
  findPrimeRowAnchorPoint,
  traceForwardEndpoint,
  BacktraceConfig,
} from "./utils/backtrace";

type ComponentLookupModule = typeof import("./utils/componentLookup");

const STORAGE_KEY = "gcdgraph-settings";
const SETTINGS_SLOTS_KEY = "gcdgraph-settings-slots";
const DEFAULT_VIEWPORT: Viewport = { x: 12, y: 8, zoom: 45 };
const DEFAULT_ROW_SHIFT_BOUNDS = { min: -210, max: 210 };
const MIN_GROUND_ROW = 1;
const DEFAULT_GROUND_ROW = 2;
const DEFAULT_DETAIL_ZOOM_CUTOFF = 20;
const MAX_HIGHLIGHT_POINTS = 500;
const MAX_SAVED_NODES = 5000;
const COMPONENT_ANCHOR_TRACE_LIMIT = 1_000_000;

const DEFAULT_AUTO_HIGHLIGHT_EXPR = "(n^3, n^2)";
const DEFAULT_MANUAL_NODES: Point[] = [
  { x: 0, y: 0 },
  { x: 0, y: 2 },
  { x: 2, y: 2 },
];

declare global {
  interface Window {
    __GCDGRAPH_SAFE_MODE__?: boolean;
  }
}

interface HighlightRange {
  min: number;
  max: number;
}

interface RowShiftBounds {
  min: number;
  max: number;
}

interface PersistedSettings {
  viewport: Viewport;
  theme: Theme;
  transformFunc: string;
  overlayPlotExpr: string;
  frontierWalk: boolean;
  moveRightExpr: string;
  simpleView: boolean;
  wraparound: boolean;
  showFactored: boolean;
  shear: boolean;
  spfTransform: boolean;
  rowShift: number;
  shiftLock: boolean;
  randomizeShift: boolean;
  degree: number;
  autoHighlightExpr: string;
  autoHighlightEnabled: boolean;
  autoHighlightGoToGround: boolean;
  autoHighlightRange: HighlightRange;
  rowShiftBounds: RowShiftBounds;
  pathStepLimit: number;
  backtraceLimit: number;
  groundRow: number;
  detailZoomCutoff: number;
  manualNodes: Point[];
  autoGeneratedNodes: Point[];
}

type SettingsSnapshot = Omit<PersistedSettings, "theme">;

interface SavedSettingsSlot {
  id: string;
  description: string;
  savedAt: number;
  snapshot: SettingsSnapshot;
}

const DEFAULT_SETTINGS_SNAPSHOT: SettingsSnapshot = {
  viewport: DEFAULT_VIEWPORT,
  transformFunc: "n",
  overlayPlotExpr: "",
  frontierWalk: false,
  moveRightExpr: DEFAULT_MOVE_RIGHT_EXPR,
  simpleView: false,
  wraparound: false,
  showFactored: true,
  shear: false,
  spfTransform: false,
  rowShift: 0,
  shiftLock: false,
  randomizeShift: false,
  degree: 1,
  autoHighlightExpr: DEFAULT_AUTO_HIGHLIGHT_EXPR,
  autoHighlightEnabled: true,
  autoHighlightGoToGround: true,
  autoHighlightRange: { min: 1, max: 25 },
  rowShiftBounds: DEFAULT_ROW_SHIFT_BOUNDS,
  pathStepLimit: 10000,
  backtraceLimit: 100000,
  groundRow: DEFAULT_GROUND_ROW,
  detailZoomCutoff: DEFAULT_DETAIL_ZOOM_CUTOFF,
  manualNodes: DEFAULT_MANUAL_NODES,
  autoGeneratedNodes: [],
};

const dedupePoints = (points: Point[]) => {
  const seen = new Set<string>();
  const result: Point[] = [];
  points.forEach((p) => {
    const x = Math.round(Number(p.x));
    const y = Math.round(Number(p.y));
    if (!Number.isFinite(x) || !Number.isFinite(y)) return;
    const key = pointKey({ x, y });
    if (seen.has(key)) return;
    seen.add(key);
    result.push({
      x,
      y,
      ...(typeof p.colorIndex === "number" ? { colorIndex: p.colorIndex } : {}),
    });
  });
  return result;
};

const clampInt = (val: number, fallback: number, min: number, max: number) => {
  if (!Number.isFinite(val)) return fallback;
  return Math.min(max, Math.max(min, Math.round(val)));
};

const parseStoredBoolean = (val: unknown): boolean | undefined => {
  if (typeof val === "boolean") return val;
  if (typeof val === "string") {
    const trimmed = val.trim().toLowerCase();
    if (trimmed === "true") return true;
    if (trimmed === "false") return false;
    return undefined;
  }
  if (typeof val === "number") {
    if (val === 1) return true;
    if (val === 0) return false;
  }
  return undefined;
};

const resolveRowShiftBounds = (
  next: Partial<RowShiftBounds> | undefined,
  fallback: RowShiftBounds
) => {
  const minRaw =
    typeof next?.min === "number" ? next.min : fallback.min;
  const maxRaw =
    typeof next?.max === "number" ? next.max : fallback.max;
  const min = clampInt(minRaw, fallback.min, -210, 210);
  const max = clampInt(maxRaw, fallback.max, -210, 210);
  return { min: Math.min(min, max), max: Math.max(min, max) };
};

function App() {
  const safeMode = window.__GCDGRAPH_SAFE_MODE__ === true;
  // Initial view centered slightly positive to show interesting initial structure
  const [viewport, setViewport] = useState<Viewport>(DEFAULT_VIEWPORT);

  const [theme, setTheme] = useState<Theme>("light");
  const [transformFunc, setTransformFunc] = useState<string>("n");
  const [overlayPlotExpr, setOverlayPlotExpr] = useState<string>("");
  const [frontierWalk, setFrontierWalk] = useState<boolean>(false);
  const [moveRightExpr, setMoveRightExpr] = useState<string>(
    DEFAULT_MOVE_RIGHT_EXPR
  );
  const [simpleView, setSimpleView] = useState(false);
  const [wraparound, setWraparound] = useState(false);
  const [showFactored, setShowFactored] = useState(true);
  const [rowShift, setRowShift] = useState<number>(0);
  const [rowShiftBounds, setRowShiftBounds] =
    useState<RowShiftBounds>(DEFAULT_ROW_SHIFT_BOUNDS);
  const [shiftLock, setShiftLock] = useState<boolean>(false);
  const [randomizeShift, setRandomizeShift] = useState<boolean>(false);
  const [cursorPos, setCursorPos] = useState<Point>({ x: 0, y: 0 });
  const [degree, setDegree] = useState<number>(1);
  const [resetPathsSignal, setResetPathsSignal] = useState<number>(0);

  const [autoHighlightExpr, setAutoHighlightExpr] = useState<string>(
    DEFAULT_AUTO_HIGHLIGHT_EXPR
  );
  const [autoHighlightEnabled, setAutoHighlightEnabled] =
    useState<boolean>(true);
  const [autoHighlightGoToGround, setAutoHighlightGoToGround] =
    useState<boolean>(true);
  const [autoHighlightRange, setAutoHighlightRange] = useState<HighlightRange>({
    min: 1,
    max: 25,
  });
  const [pathStepLimit, setPathStepLimit] = useState<number>(10000);
  const [backtraceLimit, setBacktraceLimit] = useState<number>(100000);
  const [groundRow, setGroundRow] = useState<number>(DEFAULT_GROUND_ROW);
  const [detailZoomCutoff, setDetailZoomCutoff] = useState<number>(
    DEFAULT_DETAIL_ZOOM_CUTOFF
  );
  const [backtrailLength, setBacktrailLength] = useState<number | null>(null);
  const [shear, setShear] = useState<boolean>(false);
  const [spfTransform, setSpfTransform] = useState<boolean>(false);

  const [manualNodes, setManualNodes] = useState<Point[]>(DEFAULT_MANUAL_NODES);
  const [autoGeneratedNodes, setAutoGeneratedNodes] = useState<Point[]>([]);
  const autoGeneratedNodesRef = useRef<Point[]>([]);

  const [savedSlots, setSavedSlots] = useState<SavedSettingsSlot[]>([]);
  const [settingsLoaded, setSettingsLoaded] = useState(false);
  const [slotsLoaded, setSlotsLoaded] = useState(false);
  const [componentLookupModule, setComponentLookupModule] =
    useState<ComponentLookupModule | null>(null);
  const componentLookupCacheRef = useRef<Map<string, string>>(new Map());

  const rowShiftRef = useRef(rowShift);
  const randomizeShiftRef = useRef(randomizeShift);
  const rowShiftBoundsRef = useRef<RowShiftBounds>(rowShiftBounds);

  const prevRowShiftConfig = useRef<{ k: number; randomize: boolean }>({
    k: rowShift,
    randomize: randomizeShift,
  });

  useEffect(() => {
    rowShiftRef.current = rowShift;
  }, [rowShift]);

  useEffect(() => {
    randomizeShiftRef.current = randomizeShift;
  }, [randomizeShift]);

  useEffect(() => {
    rowShiftBoundsRef.current = rowShiftBounds;
  }, [rowShiftBounds]);

  useEffect(() => {
    autoGeneratedNodesRef.current = autoGeneratedNodes;
  }, [autoGeneratedNodes]);

  const createSlotId = () => {
    if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
      return crypto.randomUUID();
    }
    return `slot-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  };

  const applySettingsSnapshot = useCallback(
    (
      data: Partial<PersistedSettings>,
      options?: { syncRowShift?: boolean; applyTheme?: boolean }
    ) => {
      const currentRowShiftBounds = rowShiftBoundsRef.current;
      const currentRowShift = rowShiftRef.current;
      const currentRandomizeShift = randomizeShiftRef.current;

      const nextRowShiftBounds = resolveRowShiftBounds(
        data.rowShiftBounds,
        currentRowShiftBounds
      );
      const nextRowShift = Number.isFinite(data.rowShift)
        ? clampInt(
            data.rowShift,
            currentRowShift,
            nextRowShiftBounds.min,
            nextRowShiftBounds.max
          )
        : clampInt(
            currentRowShift,
            currentRowShift,
            nextRowShiftBounds.min,
            nextRowShiftBounds.max
          );
      const nextRandomizeShift =
        typeof data.randomizeShift === "boolean"
          ? data.randomizeShift
          : currentRandomizeShift;

      if (options?.syncRowShift) {
        prevRowShiftConfig.current = {
          k: nextRowShift,
          randomize: nextRandomizeShift,
        };

        rowShiftRef.current = nextRowShift;
        randomizeShiftRef.current = nextRandomizeShift;
        rowShiftBoundsRef.current = nextRowShiftBounds;
      }

      if (data.viewport) setViewport(data.viewport);
      if (options?.applyTheme !== false && data.theme) setTheme(data.theme);
      if (typeof data.transformFunc === "string")
        setTransformFunc(data.transformFunc);
      if (typeof data.overlayPlotExpr === "string") {
        setOverlayPlotExpr(data.overlayPlotExpr);
      }
      if (typeof data.frontierWalk === "boolean") {
        setFrontierWalk(data.frontierWalk);
      }
      if (typeof data.moveRightExpr === "string")
        setMoveRightExpr(data.moveRightExpr);
      if (typeof data.simpleView === "boolean") setSimpleView(data.simpleView);
      const parsedWraparound = parseStoredBoolean((data as any).wraparound);
      if (typeof parsedWraparound === "boolean") {
        setWraparound(parsedWraparound);
      } else if (!Object.prototype.hasOwnProperty.call(data, "wraparound")) {
        setWraparound(false);
      }
      if (typeof data.showFactored === "boolean")
        setShowFactored(data.showFactored);
      if (typeof data.shear === "boolean") setShear(data.shear);
      if (typeof data.spfTransform === "boolean")
        setSpfTransform(data.spfTransform);
      if (data.rowShiftBounds) setRowShiftBounds(nextRowShiftBounds);
      if (data.rowShiftBounds || Number.isFinite(data.rowShift))
        setRowShift(nextRowShift);
      if (typeof data.shiftLock === "boolean") setShiftLock(data.shiftLock);
      if (typeof data.randomizeShift === "boolean")
        setRandomizeShift(nextRandomizeShift);
      if (Number.isFinite(data.degree))
        setDegree(clampInt(data.degree, 1, 1, 4));
      if (typeof data.autoHighlightExpr === "string")
        setAutoHighlightExpr(data.autoHighlightExpr);

      const parsedAutoHighlightEnabled = parseStoredBoolean(
        (data as any).autoHighlightEnabled
      );
      if (typeof parsedAutoHighlightEnabled === "boolean") {
        setAutoHighlightEnabled(parsedAutoHighlightEnabled);
      }

      const parsedGoToGround = parseStoredBoolean(
        (data as any).autoHighlightGoToGround
      );
      if (typeof parsedGoToGround === "boolean") {
        setAutoHighlightGoToGround(parsedGoToGround);
      }
      if (data.autoHighlightRange) {
        setAutoHighlightRange({
          min: clampInt(data.autoHighlightRange.min, 1, -2000, 2000),
          max: clampInt(data.autoHighlightRange.max, 25, -2000, 2000),
        });
      }
      if (Number.isFinite(data.pathStepLimit))
        setPathStepLimit(clampInt(data.pathStepLimit, 10000, 1, 1000000));
      if (Number.isFinite(data.backtraceLimit))
        setBacktraceLimit(data.backtraceLimit);
      if (Number.isFinite(data.groundRow))
        setGroundRow(
          clampInt(data.groundRow, DEFAULT_GROUND_ROW, MIN_GROUND_ROW, 2000)
        );
      if (Number.isFinite(data.detailZoomCutoff)) {
        setDetailZoomCutoff(
          clampInt(
            data.detailZoomCutoff,
            DEFAULT_DETAIL_ZOOM_CUTOFF,
            1,
            200
          )
        );
      }
      if (Array.isArray(data.manualNodes)) {
        const sliced =
          data.manualNodes.length > MAX_SAVED_NODES
            ? data.manualNodes.slice(0, MAX_SAVED_NODES)
            : data.manualNodes;
        setManualNodes(dedupePoints(sliced));
      }
      if (Array.isArray(data.autoGeneratedNodes)) {
        const sliced =
          data.autoGeneratedNodes.length > MAX_SAVED_NODES
            ? data.autoGeneratedNodes.slice(0, MAX_SAVED_NODES)
            : data.autoGeneratedNodes;
        setAutoGeneratedNodes(dedupePoints(sliced));
      }
    },
    []
  );

  const buildSettingsSnapshot = useCallback(
    (): SettingsSnapshot => ({
      viewport,
      transformFunc,
      overlayPlotExpr,
      frontierWalk,
      moveRightExpr,
      simpleView,
      wraparound,
      showFactored,
      shear,
      spfTransform,
      rowShift,
      shiftLock,
      randomizeShift,
      degree,
      autoHighlightExpr,
      autoHighlightEnabled,
      autoHighlightGoToGround,
      autoHighlightRange: { ...autoHighlightRange },
      rowShiftBounds,
      pathStepLimit,
      backtraceLimit,
      groundRow,
      detailZoomCutoff,
      manualNodes: dedupePoints(manualNodes),
      autoGeneratedNodes: dedupePoints(autoGeneratedNodes),
    }),
    [
      viewport,
      transformFunc,
      overlayPlotExpr,
      frontierWalk,
      moveRightExpr,
      simpleView,
      wraparound,
      showFactored,
      shear,
      spfTransform,
      rowShift,
      shiftLock,
      randomizeShift,
      degree,
      autoHighlightExpr,
      autoHighlightEnabled,
      autoHighlightGoToGround,
      autoHighlightRange,
      rowShiftBounds,
      pathStepLimit,
      backtraceLimit,
      groundRow,
      detailZoomCutoff,
      manualNodes,
      autoGeneratedNodes,
    ]
  );

  // Load persisted settings
  useEffect(() => {
    if (window.__GCDGRAPH_SAFE_MODE__) {
      setSettingsLoaded(true);
      return;
    }
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) {
      setSettingsLoaded(true);
      return;
    }
    try {
      const data = JSON.parse(raw);
      applySettingsSnapshot(data, { syncRowShift: true });

      // Defer the "loaded" flag to avoid writing defaults back to storage
      // during the same commit that applies the loaded snapshot.
      queueMicrotask(() => setSettingsLoaded(true));
      return;
    } catch (err) {
      console.error("Failed to load settings", err);
      try {
        localStorage.removeItem(STORAGE_KEY);
      } catch {}
    }

    setSettingsLoaded(true);
  }, []);

  // Load saved slots
  useEffect(() => {
    if (window.__GCDGRAPH_SAFE_MODE__) {
      setSlotsLoaded(true);
      return;
    }
    const raw = localStorage.getItem(SETTINGS_SLOTS_KEY);
    if (!raw) {
      setSlotsLoaded(true);
      return;
    }
    try {
      const data = JSON.parse(raw);
      if (Array.isArray(data)) {
        const cleaned = data
          .map((slot) => {
            if (!slot || typeof slot !== "object") return null;
            const description =
              typeof slot.description === "string"
                ? slot.description.trim()
                : "";
            if (!description) return null;
            const snapshot =
              slot.snapshot && typeof slot.snapshot === "object"
                ? (({ theme: _theme, ...rest }) => rest)(slot.snapshot as PersistedSettings)
                : null;
            if (!snapshot) return null;
            const id =
              typeof slot.id === "string" && slot.id
                ? slot.id
                : createSlotId();
            const savedAt = Number.isFinite(slot.savedAt)
              ? slot.savedAt
              : Date.now();
            return {
              id,
              description,
              savedAt,
              snapshot,
            } as SavedSettingsSlot;
          })
          .filter((slot): slot is SavedSettingsSlot => Boolean(slot));
        setSavedSlots(cleaned);
      }
    } catch (err) {
      console.error("Failed to load saved slots", err);
      try {
        localStorage.removeItem(SETTINGS_SLOTS_KEY);
      } catch {}
    } finally {
      setSlotsLoaded(true);
    }
  }, []);

  // Persist settings
  useEffect(() => {
    if (!settingsLoaded || safeMode) return;
    const payload = {
      viewport,
      theme,
      transformFunc,
      overlayPlotExpr,
      frontierWalk,
      moveRightExpr,
      simpleView,
      wraparound,
      showFactored,
      shear,
      spfTransform,
      rowShift,
      shiftLock,
      randomizeShift,
      degree,
      autoHighlightExpr,
      autoHighlightEnabled,
      autoHighlightGoToGround,
      autoHighlightRange,
      rowShiftBounds,
      pathStepLimit,
      backtraceLimit,
      groundRow,
      manualNodes,
      autoGeneratedNodes,
    };
    localStorage.setItem(STORAGE_KEY, JSON.stringify(payload));
  }, [
    settingsLoaded,
    safeMode,
    viewport,
    theme,
    transformFunc,
    overlayPlotExpr,
    frontierWalk,
    moveRightExpr,
    simpleView,
    wraparound,
    showFactored,
    shear,
    spfTransform,
    rowShift,
    shiftLock,
    randomizeShift,
    degree,
    autoHighlightExpr,
    autoHighlightEnabled,
    autoHighlightGoToGround,
    autoHighlightRange,
    rowShiftBounds,
    pathStepLimit,
    backtraceLimit,
    groundRow,
    manualNodes,
    autoGeneratedNodes,
  ]);

  // Persist saved slots
  useEffect(() => {
    if (!slotsLoaded || safeMode) return;
    localStorage.setItem(SETTINGS_SLOTS_KEY, JSON.stringify(savedSlots));
  }, [savedSlots, slotsLoaded, safeMode]);

  // Shift manual path starts when unlocked so they follow row adjustments
  useEffect(() => {
    const previous = prevRowShiftConfig.current;
    const sameConfig =
      previous.k === rowShift && previous.randomize === randomizeShift;

    if (shiftLock || sameConfig) {
      prevRowShiftConfig.current = { k: rowShift, randomize: randomizeShift };
      return;
    }

    setManualNodes((starts) => {
      if (starts.length === 0) return starts;

      let changed = false;
      const next = starts.map((p) => {
        const delta =
          getRowOffset(p.y, rowShift, randomizeShift) -
          getRowOffset(p.y, previous.k, previous.randomize);
        if (delta === 0) return p;
        changed = true;
        return { ...p, x: p.x + delta };
      });

      return changed ? next : starts;
    });

    prevRowShiftConfig.current = { k: rowShift, randomize: randomizeShift };
  }, [rowShift, shiftLock, randomizeShift]);

  const sanitizedRange = useMemo(() => {
    const min = clampInt(autoHighlightRange.min, 1, -2000, 2000);
    const max = clampInt(autoHighlightRange.max, 25, -2000, 2000);
    return {
      min: Math.min(min, max),
      max: Math.max(min, max),
    };
  }, [autoHighlightRange]);

  const evaluateAutoExpr = useCallback(
    (expr: string) => {
      const trimmed = expr.trim();
      if (!trimmed) return { points: [] as Point[], error: "" };

      const tupleMatch = trimmed.match(/^\s*\(?\s*(.+)\s*,\s*(.+)\b\s*\)?\s*$/);
      if (!tupleMatch) {
        return {
          points: [] as Point[],
          error:
            "Use format (xExpr, yExpr) with comma-separated expressions in n.",
        };
      }

      const xExpr = tupleMatch[1];
      const yExpr = tupleMatch[2];
      console.log("Evaluating auto highlight expressions:", { xExpr, yExpr });
      const xFn = createTransformFunction(xExpr);
      const yFn = createTransformFunction(yExpr);

      const startN = Math.round(sanitizedRange.min);
      const endN = Math.round(sanitizedRange.max);
      const total = endN - startN + 1;
      if (total > MAX_HIGHLIGHT_POINTS) {
        return {
          points: [] as Point[],
          error: `Range too large (max ${MAX_HIGHLIGHT_POINTS} values).`,
        };
      }

      const points: Point[] = [];
      const seen = new Set<string>();

      for (let n = startN; n <= endN; n++) {
        const xVal = xFn(n);
        const yVal = yFn(n);
        const x = Math.round(xVal);
        const y = Math.round(yVal);

        if (!Number.isFinite(x) || !Number.isFinite(y)) {
          return {
            points: [] as Point[],
            error: "Expression produced a non-finite value.",
          };
        }

        const key = pointKey({ x, y });
        if (!seen.has(key)) {
          seen.add(key);
          points.push({ x, y, colorIndex: n });
        }
      }

      return { points, error: "" };
    },
    [sanitizedRange]
  );

  const autoHighlightResult = useMemo(
    () => evaluateAutoExpr(autoHighlightExpr),
    [autoHighlightExpr, evaluateAutoExpr]
  );

  const overlayPlotError = useMemo(() => {
    const trimmed = overlayPlotExpr.trim();
    if (!trimmed) return undefined;
    const expressions = splitTopLevelExpressions(trimmed);
    if (expressions.length === 0) return "Invalid plot expression.";

    const hasInvalidExpression = expressions.some(
      (expr) => !createTransformFunction(expr).isValid
    );
    if (!hasInvalidExpression) return undefined;
    return expressions.length === 1
      ? "Invalid plot expression."
      : "One or more plot expressions are invalid.";
  }, [overlayPlotExpr]);

  const moveRight = useMemo(
    () => compileMoveRightPredicate(moveRightExpr),
    [moveRightExpr]
  );

  const isStandardComponentBaseCase = useMemo(() => {
    const transformToken = transformFunc.trim().toLowerCase();
    return (
      moveRight.fn.isDefaultCoprimeRule === true &&
      (transformToken === "" || transformToken === "n" || transformToken === "x") &&
      rowShift === 0 &&
      !randomizeShift &&
      !shear &&
      !wraparound
    );
  }, [
    moveRight.fn.isDefaultCoprimeRule,
    randomizeShift,
    rowShift,
    shear,
    transformFunc,
    wraparound,
  ]);

  const canUseExactComponentCache = isStandardComponentBaseCase;

  useEffect(() => {
    componentLookupCacheRef.current.clear();
  }, [componentLookupModule]);

  useEffect(() => {
    if (!canUseExactComponentCache || componentLookupModule) return;

    let cancelled = false;
    import("./utils/componentLookup").then((mod) => {
      if (!cancelled) setComponentLookupModule(mod);
    });

    return () => {
      cancelled = true;
    };
  }, [canUseExactComponentCache, componentLookupModule]);

  const componentDisplay = useMemo(() => {
    const isStandardBaseCase = canUseExactComponentCache;

    const cache = componentLookupCacheRef.current;
    const cacheKey = [
      cursorPos.x,
      cursorPos.y,
      spfTransform ? 1 : 0,
      isStandardBaseCase ? 1 : 0,
      componentLookupModule ? 1 : 0,
    ].join("|");
    const cached = cache.get(cacheKey);
    if (cached !== undefined) return cached;

    let nextDisplay = "n/a";

    if (isStandardBaseCase) {
      if (!componentLookupModule) {
        nextDisplay = "loading...";
      } else {
        const getEffectiveX = (gx: number, _gy: number) => gx;
        const checkGoesNorth = (gx: number, gy: number) => {
          const x = Math.round(gx);
          const y = Math.round(gy);
          const ruleY = spfTransform ? getSmallestPrimeFactor(y) : y;
          return gcd(x, ruleY) !== 1;
        };
        const getNorthStepY = (_currX: number, currY: number) => currY + 1;

        const componentConfig: BacktraceConfig = {
          checkGoesNorth,
          getNorthStepY,
          getEffectiveX,
          groundRow: 2,
          backtraceLimit,
          canFastForward: true,
          wraparound: false,
          transform: (n: number) => n,
          getDefaultRuleTargetValue: (n: number) =>
            spfTransform ? getSmallestPrimeFactor(n) : n,
          isDefaultCoprimeRule: true,
        };

        const getDisplayForPoint = (target: Point): string | null => {
          const groundPoint = findGroundPoint(target, componentConfig);
          if (groundPoint.y !== 2) return null;
          const componentNumber = componentLookupModule.findComponentNumberAtRow2(
            groundPoint.x,
            spfTransform
          );
          if (componentNumber !== null) {
            return componentNumber.toLocaleString();
          }
          return `>${componentLookupModule
            .getKnownComponentCount(spfTransform)
            .toLocaleString()}`;
        };

        const cursorPoint = {
          x: Math.round(cursorPos.x),
          y: Math.round(cursorPos.y),
        };
        const primeAnchor = findPrimeRowAnchorPoint(
          cursorPoint,
          Math.min(
            COMPONENT_ANCHOR_TRACE_LIMIT,
            Math.max(1_000, backtraceLimit)
          ),
          componentConfig
        );
        nextDisplay =
          getDisplayForPoint(primeAnchor ?? cursorPoint) ?? "n/a";
      }
    }

    if (cache.size >= 5000) cache.clear();
    cache.set(cacheKey, nextDisplay);
    return nextDisplay;
  }, [
    backtraceLimit,
    canUseExactComponentCache,
    componentLookupModule,
    cursorPos.x,
    cursorPos.y,
    spfTransform,
  ]);

  const togglePathStart = useCallback((p: Point) => {
    const key = pointKey(p);
    setManualNodes((prev) => {
      if (prev.some((pt) => pointKey(pt) === key)) {
        return prev.filter((pt) => pointKey(pt) !== key);
      }
      return [...prev, p];
    });
  }, []);

  const applyAutoHighlight = useCallback(
    (expr: string, enabled: boolean) => {
      const result = evaluateAutoExpr(expr);
      setAutoHighlightExpr((prev) => (prev === expr ? prev : expr));
      setAutoHighlightEnabled((prev) => (prev === enabled ? prev : enabled));

      const activeTransform = createTransformFunction(transformFunc);
      const moveRightPredicate = moveRight.fn;

      const getEffectiveX = (gx: number, gy: number) => {
        const shearedX = shear ? gx + gy : gx;
        const offset = getRowShiftMagnitude(gy, rowShift, randomizeShift);
        if (offset > 0) {
          if (gy > 0) return shearedX - offset;
          if (gy < 0) return shearedX + offset;
        }
        return shearedX;
      };

      const computeBigGcd = (gx: number, gy: number): bigint | null => {
        if (!moveRightPredicate.isDefaultCoprimeRule) return null;
        if (!activeTransform.evalBigInt) return null;

        const xInt = Math.round(getEffectiveX(gx, gy));
        const yInt = Math.round(gy);

        const xBig = BigInt(xInt);
        const yBig = BigInt(yInt);

        const vXBig = activeTransform.evalBigInt(xBig);
        const vYBig = activeTransform.evalBigInt(yBig);
        if (vXBig === null || vYBig === null) return null;

        const ruleYBig = spfTransform
          ? getSmallestPrimeFactorBigInt(vYBig)
          : vYBig;
        return gcdBigInt(vXBig, ruleYBig);
      };

      const checkGoesNorth = (gx: number, gy: number) => {
        const gcdExact = computeBigGcd(gx, gy);
        if (gcdExact !== null) return gcdExact !== 1n;

        const effectiveX = getEffectiveX(gx, gy);
        const rawX = Math.round(effectiveX);
        const rawY = Math.round(gy);
        const vX = Math.round(activeTransform(effectiveX));
        const vY = Math.round(activeTransform(gy));
        const ruleY = spfTransform ? getSmallestPrimeFactor(vY) : vY;

        if (moveRightPredicate.isDefaultCoprimeRule) {
          return gcd(vX, ruleY) !== 1;
        }
        try {
          return !moveRightPredicate(rawX, rawY, activeTransform);
        } catch {
          return gcd(vX, vY) !== 1;
        }
      };

      const getNorthStepY = (currX: number, currY: number) => {
        const nextY = currY + 1;
        if (wraparound && nextY === currX) return 0;
        return nextY;
      };

      const canFastForward =
          moveRightPredicate.isDefaultCoprimeRule === true &&
          (transformFunc.trim().toLowerCase() === "n" ||
            transformFunc.trim().toLowerCase() === "x");

      const groundY = clampInt(
        groundRow,
        DEFAULT_GROUND_ROW,
        MIN_GROUND_ROW,
        2000
      );

      const btConfig: BacktraceConfig = {
        checkGoesNorth,
        getNorthStepY,
        getEffectiveX,
        groundRow: groundY,
        backtraceLimit,
        canFastForward,
        wraparound,
        transform: (n: number) => Math.round(activeTransform(n)),
        getDefaultRuleTargetValue: (n: number) => {
          const transformedY = Math.round(activeTransform(n));
          return spfTransform
            ? getSmallestPrimeFactor(transformedY)
            : transformedY;
        },
        isDefaultCoprimeRule: Boolean(moveRightPredicate.isDefaultCoprimeRule),
      };

      const nextAutoPoints =
        !enabled || result.error || result.points.length === 0
          ? ([] as Point[])
          : autoHighlightGoToGround
          ? dedupePoints(
              result.points.map((start) => {
                if (start.y <= groundY) return start;
                const end = traceForwardEndpoint(start, 1000, btConfig);
                const groundPoint = findGroundPoint(end, btConfig);
                return {
                  ...groundPoint,
                  ...(typeof start.colorIndex === "number"
                    ? { colorIndex: start.colorIndex }
                    : {}),
                };
              })
            )
          : result.points;

      const previousAutoPoints = autoGeneratedNodesRef.current;

      if (!enabled || result.error || nextAutoPoints.length === 0) {
        const autoKeys = new Set(previousAutoPoints.map((p) => pointKey(p)));
        setManualNodes((prev) =>
          prev.filter((p) => !autoKeys.has(pointKey(p)))
        );
        setAutoGeneratedNodes([]);
        return;
      }

      const autoKeys = new Set(previousAutoPoints.map((p) => pointKey(p)));
      setManualNodes((prev) => {
        const retained = prev.filter((p) => !autoKeys.has(pointKey(p)));
        return dedupePoints([...retained, ...nextAutoPoints]);
      });
      setAutoGeneratedNodes(nextAutoPoints);
    },
    [
      autoHighlightGoToGround,
      backtraceLimit,
      evaluateAutoExpr,
      groundRow,
      moveRight.fn,
      randomizeShift,
      rowShift,
      shear,
      spfTransform,
      transformFunc,
      wraparound,
    ]
  );

  useEffect(() => {
    if (!settingsLoaded) return;
    if (!autoHighlightEnabled) return;
    applyAutoHighlight(autoHighlightExpr, true);
  }, [settingsLoaded, autoHighlightEnabled, autoHighlightExpr, applyAutoHighlight]);

  const resetPaths = useCallback(() => {
    setManualNodes([]);
    setAutoGeneratedNodes([]);
    setResetPathsSignal((s) => s + 1);
  }, []);

  const handleRangeChange = useCallback((next: Partial<HighlightRange>) => {
    setAutoHighlightRange((prev) => {
      const updated = { ...prev, ...next };
      return {
        min: clampInt(updated.min, 1, -2000, 2000),
        max: clampInt(updated.max, 25, -2000, 2000),
      };
    });
  }, []);

  const handleRowShiftBounds = useCallback((next: Partial<RowShiftBounds>) => {
    setRowShiftBounds((prev) => {
      const updated = resolveRowShiftBounds(next, prev);
      setRowShift((current) =>
        clampInt(current, current, updated.min, updated.max)
      );
      return updated;
    });
  }, []);

  const handlePathStepLimit = useCallback(
    (val: number) =>
      setPathStepLimit(clampInt(val, pathStepLimit, 1, 1000000)),
    [pathStepLimit]
  );

  const handleBacktraceLimit = useCallback(
    (val: number) => setBacktraceLimit(val),
    []
  );

  const handleGroundRow = useCallback(
    (val: number) =>
      setGroundRow(
        clampInt(val, groundRow, MIN_GROUND_ROW, 2000)
      ),
    [groundRow]
  );

  const handleDetailZoomCutoff = useCallback(
    (val: number) =>
      setDetailZoomCutoff(
        clampInt(val, detailZoomCutoff, 1, 200)
      ),
    [detailZoomCutoff]
  );

  const handleSaveSlot = useCallback(
    (description: string) => {
      const trimmed = description.trim();
      if (!trimmed) return;
      const snapshot = buildSettingsSnapshot();
      const nextSlot: SavedSettingsSlot = {
        id: createSlotId(),
        description: trimmed,
        savedAt: Date.now(),
        snapshot,
      };
      setSavedSlots((prev) => [nextSlot, ...prev]);
    },
    [buildSettingsSnapshot]
  );

  const handleLoadSlot = useCallback(
    (slotId: string) => {
      if (slotId === "default") {
        applySettingsSnapshot(DEFAULT_SETTINGS_SNAPSHOT, {
          syncRowShift: true,
          applyTheme: false,
        });
        return;
      }
      const slot = savedSlots.find((item) => item.id === slotId);
      if (!slot) return;
      applySettingsSnapshot(slot.snapshot, {
        syncRowShift: true,
        applyTheme: false,
      });
    },
    [applySettingsSnapshot, savedSlots]
  );

  const handleDeleteSlot = useCallback((slotId: string) => {
    if (slotId === "default") return;
    setSavedSlots((prev) => prev.filter((slot) => slot.id !== slotId));
  }, []);

  const slotSummaries = useMemo(
    () =>
      [
        { id: "default", description: "Default" },
        ...savedSlots.map(({ id, description }) => ({
          id,
          description,
        })),
      ],
    [savedSlots]
  );

  return (
    <div
      className={`relative w-full h-full overflow-hidden transition-colors duration-300 select-none ${
        theme === "dark" ? "bg-gray-900" : "bg-gray-50"
      }`}
    >
      <InfiniteGraph
        viewport={viewport}
        onViewportChange={setViewport}
        theme={theme}
        transformFunc={transformFunc}
        overlayPlotExpr={overlayPlotExpr}
        frontierWalk={frontierWalk}
        moveRightPredicate={moveRight.fn}
        simpleView={simpleView}
        showFactored={showFactored}
        rowShift={rowShift}
        randomizeShift={randomizeShift}
        wraparound={wraparound}
        onCursorMove={setCursorPos}
        degree={degree}
        resetPathsSignal={resetPathsSignal}
        pathStarts={manualNodes}
        onTogglePathStart={togglePathStart}
        pathStepLimit={pathStepLimit}
        backtraceLimit={backtraceLimit}
        groundRow={groundRow}
        detailZoomCutoff={detailZoomCutoff}
        onBacktrailChange={(len) => setBacktrailLength(len)}
        shear={shear}
        spfTransform={spfTransform}
      />
      <Controls
        viewport={viewport}
        setViewport={setViewport}
        theme={theme}
        setTheme={setTheme}
        transformFunc={transformFunc}
        setTransformFunc={setTransformFunc}
        overlayPlotExpr={overlayPlotExpr}
        setOverlayPlotExpr={setOverlayPlotExpr}
        overlayPlotError={overlayPlotError}
        frontierWalk={frontierWalk}
        setFrontierWalk={setFrontierWalk}
        moveRightExpr={moveRightExpr}
        setMoveRightExpr={setMoveRightExpr}
        moveRightError={moveRight.error}
        simpleView={simpleView}
        setSimpleView={setSimpleView}
        wraparound={wraparound}
        setWraparound={setWraparound}
        showFactored={showFactored}
        setShowFactored={setShowFactored}
        rowShift={rowShift}
        setRowShift={setRowShift}
        rowShiftBounds={rowShiftBounds}
        setRowShiftBounds={handleRowShiftBounds}
        shiftLock={shiftLock}
        setShiftLock={setShiftLock}
        randomizeShift={randomizeShift}
        setRandomizeShift={setRandomizeShift}
        cursorPos={cursorPos}
        degree={degree}
        setDegree={setDegree}
        onResetPaths={resetPaths}
        autoHighlightExpr={autoHighlightExpr}
        autoHighlightEnabled={autoHighlightEnabled}
        onApplyAutoHighlight={applyAutoHighlight}
        autoHighlightGoToGround={autoHighlightGoToGround}
        setAutoHighlightGoToGround={setAutoHighlightGoToGround}
        autoHighlightError={autoHighlightResult.error}
        autoHighlightRange={sanitizedRange}
        setAutoHighlightRange={handleRangeChange}
        pathStepLimit={pathStepLimit}
        setPathStepLimit={handlePathStepLimit}
        backtraceLimit={backtraceLimit}
        setBacktraceLimit={handleBacktraceLimit}
        groundRow={groundRow}
        setGroundRow={handleGroundRow}
        detailZoomCutoff={detailZoomCutoff}
        setDetailZoomCutoff={handleDetailZoomCutoff}
        backtrailLength={backtrailLength}
        componentDisplay={componentDisplay}
        savedSlots={slotSummaries}
        onSaveSlot={handleSaveSlot}
        onLoadSlot={handleLoadSlot}
        onDeleteSlot={handleDeleteSlot}
        shear={shear}
        setShear={setShear}
        spfTransform={spfTransform}
        setSpfTransform={setSpfTransform}
      />
      {/* Branding / Watermark */}
      <div className="absolute bottom-4 left-4 pointer-events-none opacity-50">
        <span
          className={`text-xs font-mono ${
            theme === "dark" ? "text-gray-600" : "text-gray-400"
          }`}
        >
          Infinite GCD Explorer
        </span>
      </div>
    </div>
  );
}

export default App;
